### ISSUE TITLE
api functions

### ISSUE THREAD

**Issue by proexidno** [proexidno/CardLearner#2]
Names of function may differ 
**chatID is the same as userID**

# Api should include functions:

### getLearnWord(chatID int64) Word, error
Which return a random word from a list of global words that this user have never seen
error should equal nil unless there is an error when accessing database

### getReviseWord(chatID int64) Word, error
Which should return a random word from a list of words that this user have seen and should revise (determined by time)
OR nil when there are no words that user can revise
error should equal nil unless there is an error when accessing database

### setWord(word Word, isLearned bool, chatID int64) error
Sets word for this user to the next level or revision if isLearned is false
Sets word for this user to be learned (max level of revision) isLearned is true
error should equal nil unless there is an error when accessing database

### initDatabase() error
Which should initialize tables and fill them with words
error should equal nil unless there is an error when accessing database

For now that is all

**Comment by Dkwia** [comment]
- Add all methods that u provided
- Add `test()` method for debug
